export interface ITrainee {
  id: string,
  name: string,
  grade: number,
  email: string,
  dateJoined: string,
  address: string,
  city: string,
  country: string,
  zip: number,
  subject: string,
  average: number,
  exams: number
}

export const MOCK_DATA: ITrainee[] = [
  {
    id: "1",
    name: "Bar Ferebee",
    grade: 31,
    email: "cferebee0@google.ru",
    average: 83,
    exams: 3,
    dateJoined: "23/11/2023",
    address: "Ryan",
    city: "Houjiagang",
    country: 'Israel',
    zip: 136961,
    subject: "EEOC"
  },
  {
    id: "2",
    name: "Bar Dunkerly",
    grade: 96,
    email: "bdunkerly1@yolasite.com",
    average: 13,
    exams: 3,
    dateJoined: "02/04/2024",
    address: "Kenwood",
    city: "Belyye Stolby",
    country: 'Israel',
    zip: 914898,
    subject: "Alternative Medicine"
  },
  {
    id: "3",
    name: "Arley Dumke",
    grade: 74,
    email: "adumke2@lycos.com",
    average: 83,
    exams: 3,
    dateJoined: "24/08/2024",
    address: "Pond",
    city: "Quma",
    country: 'Israel',
    zip: 655506,
    subject: "SDS-PAGE"
  },
  {
    id: "4",
    name: "Gregorius Lashford",
    grade: 33,
    email: "glashford3@abc.net.au",
    average: 20,
    exams: 3,
    dateJoined: "27/11/2023",
    address: "Longview",
    city: "Shuangfeng",
    country: 'Israel',
    zip: 285216,
    subject: "SFDC"
  },
  {
    id: "5",
    name: "Flin Dehn",
    grade: 16,
    email: "fdehn4@rambler.ru",
    average: 43,
    exams: 3,
    dateJoined: "04/07/2024",
    address: "Oak",
    city: "Fayzabad",
    country: 'Israel',
    zip: 157573,
    subject: "Software Project Management"
  },
  {
    id: "6",
    name: "Rosana Shutt",
    grade: 19,
    email: "rshutt5@lulu.com",
    average: 83,
    exams: 3,
    dateJoined: "11/01/2024",
    address: "Swallow",
    city: "Xinzhan",
    country: 'Israel',
    zip: 553452,
    subject: "Workshops"
  },
  {
    id: "7",
    name: "Lana Bartell",
    grade: 31,
    email: "lbartell6@wp.com",
    average: 53,
    exams: 3,
    dateJoined: "25/12/2023",
    address: "Brentwood",
    city: "Arklow",
    country: 'Israel',
    zip: 105372,
    subject: "Geology"
  },
  {
    id: "8",
    name: "Ottilie Bosdet",
    grade: 45,
    email: "obosdet7@earthlink.net",
    average: 83,
    exams: 3,
    dateJoined: "10/03/2024",
    address: "Pepper Wood",
    city: "Nanzhao",
    country: 'Israel',
    zip: 119631,
    subject: "CBP"
  },
  {
    id: "9",
    name: "Kathie Heninghem",
    grade: 85,
    email: "kheninghem8@alexa.com",
    average: 65,
    exams: 3,
    dateJoined: "04/12/2023",
    address: "Eastlawn",
    city: "Okulovka",
    country: 'Israel',
    zip: 147093,
    subject: "Hydraulic Fracturing"
  },
  {
    id: "10",
    name: "Gilbert Sell",
    grade: 57,
    email: "gsell9@ucsd.edu",
    average: 83,
    exams: 3,
    dateJoined: "31/10/2023",
    address: "Warbler",
    city: "Roissy Charles-de-Gaulle",
    country: 'Israel',
    zip: 785783,
    subject: "XPAC"
  },
  {
    id: "11",
    name: "Denise Buxsy",
    grade: 39,
    email: "dbuxsya@bing.com",
    average: 54,
    exams: 3,
    dateJoined: "21/08/2024",
    address: "Monterey",
    city: "Mahébourg",
    country: 'Israel',
    zip: 371563,
    subject: "Oil &amp; Gas"
  },
  {
    id: "12",
    name: "Alis Mitrikhin",
    grade: 20,
    email: "amitrikhinb@blogger.com",
    average: 83,
    exams: 3,
    dateJoined: "13/11/2023",
    address: "Fulton",
    city: "Luopioinen",
    country: 'Israel',
    zip: 907488,
    subject: "MS Axapta"
  },
  {
    id: "13",
    name: "Derril Mattaser",
    grade: 1,
    email: "dmattaserc@digg.com",
    average: 54,
    exams: 3,
    dateJoined: "21/09/2023",
    address: "Bellgrove",
    city: "Lunang",
    country: 'Israel',
    zip: 158271,
    subject: "Multi-Unit Management"
  },
  {
    id: "14",
    name: "Garrek Macauley",
    grade: 26,
    email: "gmacauleyd@geocities.jp",
    average: 83,
    exams: 3,
    dateJoined: "28/10/2023",
    address: "Hansons",
    city: "Fuvahmulah",
    country: 'Israel',
    zip: 701139,
    subject: "Psychopharmacology"
  },
  {
    id: "15",
    name: "Seana Wolledge",
    grade: 45,
    email: "swolledgee@prlog.org",
    average: 54,
    exams: 3,
    dateJoined: "03/05/2024",
    address: "Mayfield",
    city: "Sukorejo",
    country: 'Israel',
    zip: 394387,
    subject: "AKTA"
  },
  {
    id: "16",
    name: "Kaitlin Mordecai",
    grade: 36,
    email: "kmordecaif@t.co",
    average: 83,
    exams: 3,
    dateJoined: "25/06/2024",
    address: "Londonderry",
    city: "São Gabriel",
    country: 'Israel',
    zip: 937117,
    subject: "IntelliJ IDEA"
  },
  {
    id: "17",
    name: "Inesita Parzizek",
    grade: 79,
    email: "iparzizekg@sfgate.com",
    average: 83,
    exams: 3,
    dateJoined: "31/08/2024",
    address: "Twin Pines",
    city: "Pellegrini",
    country: 'Israel',
    zip: 788191,
    subject: "TSM Administration"
  },
  {
    id: "18",
    name: "Adel Brimmell",
    grade: 19,
    email: "abrimmellh@topsy.com",
    average: 83,
    exams: 3,
    dateJoined: "31/10/2023",
    address: "Spohn",
    city: "Shuanggang",
    country: 'Israel',
    zip: 73808,
    subject: "Pyramid"
  },
  {
    id: "19",
    name: "Ricky Kuscha",
    grade: 54,
    email: "rkuschai@cloudflare.com",
    average: 83,
    exams: 3,
    dateJoined: "07/12/2023",
    address: "Kennedy",
    city: "Rudka",
    country: 'Israel',
    zip: 228406,
    subject: "FDDI"
  },
  {
    id: "20",
    name: "Ivonne Tebbit",
    grade: 59,
    email: "itebbitj@va.gov",
    average: 83,
    exams: 3,
    dateJoined: "04/08/2024",
    address: "Ridgeway",
    city: "Jesenice",
    country: 'Israel',
    zip: 404452,
    subject: "PFP"
  }
]
